// ===================== DELI NPC SYSTEM =====================
// Two NPC types:
//   Order NPC  — ONLY enters when food is on counter. Pick up → sit → eat 15s → leave.
//   Aisle NPC  — Enters anytime. Browses shelves with a bag that fills up. Player gets paid.
//
// Orders are auto-generated by cookingSystem. Player preps food and serves at
// the green SERVE counter. Completed orders appear as plates on the brown counter.
// NO pathfinding — straight-line movement between defined waypoints.

// ===================== APPEARANCE POOL =====================
const DELI_NPC_APPEARANCES = [
  { skin: '#d4a574', hair: '#3a2a1a', shirt: '#4060a0', pants: '#3a3a50' },
  { skin: '#8d5524', hair: '#1a1a1a', shirt: '#a04040', pants: '#2a3a4a' },
  { skin: '#f0c8a0', hair: '#c08040', shirt: '#40a060', pants: '#4a4a5a' },
  { skin: '#c68642', hair: '#4a3020', shirt: '#d0a040', pants: '#3a4a3a' },
  { skin: '#e0b890', hair: '#8a6a40', shirt: '#6040a0', pants: '#3a3a4a' },
  { skin: '#a0764a', hair: '#2a1a0a', shirt: '#a06030', pants: '#4a3a30' },
  { skin: '#f5d0a0', hair: '#d0a060', shirt: '#306060', pants: '#504040' },
  { skin: '#b5835a', hair: '#1a1010', shirt: '#808080', pants: '#2a2a3a' },
];

// Real human names for NPCs
const DELI_NPC_NAMES = [
  'Tyler', 'Hailey', 'Johnny', 'Marcus', 'Sophia', 'Derek', 'Lily', 'Brandon',
  'Emma', 'Chris', 'Maya', 'Jake', 'Olivia', 'Andre', 'Chloe', 'Ethan',
  'Zoe', 'Kevin', 'Rachel', 'Dylan', 'Mia', 'Jordan', 'Sarah', 'Liam',
  'Ava', 'Noah', 'Grace', 'Alex', 'Hannah', 'Ryan', 'Kayla', 'Mason',
];

// ===================== DEFINED SPOTS =====================
// Door is 4 tiles wide (tx:12-15). Left side = enter, right side = exit.
const DELI_SPOTS = {
  enterDoor:   { tx: 13, ty: 34 },   // left side of door — NPCs enter here
  exitDoor:    { tx: 14, ty: 34 },   // right side of door — NPCs exit here
  counterArea: { tx: 13, ty: 22 },   // corridor in front of counter
  corridorE:   { tx: 25, ty: 22 },   // east end — past the counter wall
  diningEntry: { tx: 26, ty: 20 },   // gap into dining area
};

// Pickup spots aligned with plate render positions on the service counter (ty:22, south of counter wall at ty:21)
// Plates render at tx:14,15,16,17 on the counter — NPC must stand directly in front facing north
const DELI_PICKUP_SPOTS = [
  { tx: 14, ty: 22 }, { tx: 15, ty: 22 }, { tx: 16, ty: 22 }, { tx: 17, ty: 22 },
];

// Chairs (NPCs sit here) — LEFT and RIGHT sides only (no top/bottom corners)
const DELI_CHAIRS = [
  // Table 1 (28,4) — side chairs only
  { tx: 27, ty: 4,  sitDir: 3 },  { tx: 27, ty: 5,  sitDir: 3 },   // left ×2
  { tx: 31, ty: 4,  sitDir: 2 },  { tx: 31, ty: 5,  sitDir: 2 },   // right ×2
  // Table 2 (28,17) — side chairs only
  { tx: 27, ty: 17, sitDir: 3 },  { tx: 27, ty: 18, sitDir: 3 },
  { tx: 31, ty: 17, sitDir: 2 },  { tx: 31, ty: 18, sitDir: 2 },
];

// Aisle shelves — each has 2 browse spots (not corners, 1-tile gap between).
// NPCs stand 1 tile below shelf and face north to browse. Max 2 NPCs per shelf.
const DELI_SHELVES = [
  { name: 'Frozen',    price: 4, spots: [{ tx: 28, ty: 26 }, { tx: 30, ty: 26 }] },
  { name: 'Snacks',    price: 3, spots: [{ tx: 35, ty: 26 }, { tx: 37, ty: 26 }] },
  { name: 'Candy',     price: 2, spots: [{ tx: 28, ty: 32 }, { tx: 30, ty: 32 }] },
  { name: 'Beverages', price: 3, spots: [{ tx: 35, ty: 32 }, { tx: 37, ty: 32 }] },
];

// Backward-compat alias (referenced by entity renderer for plate rendering)
const DELI_AISLES = DELI_SHELVES;

// Cashier spot for retail shoppers (tx:37 keeps NPC body off right wall)
const DELI_CASHIER = { tx: 37, ty: 24 };

// ===================== CONFIG =====================
const DELI_NPC_CONFIG = {
  minNPCs: 0,
  maxNPCs: 6,
  spawnInterval: [180, 420],   // 3-7 sec randomized range (frames at 60fps)
  baseSpeed: 0.77,             // slow relaxed stroll
  speedVariance: 0.14,
  eatDuration:    [900, 900],  // 15 sec at 60fps
  browseDuration: [480, 900],  // 8-15 sec browsing at an aisle
  aisleSpawnInterval: [1800, 1800], // 30 sec between aisle NPC spawns
};

// ===================== STATE =====================
const deliNPCs = [];
const _deliIdCounter = { value: 0 };
const _deliSpawnState = { timer: 0, nextInterval: 600 };
let _deliAisleSpawnTimer = 0;

// ===================== HELPERS =====================

// Kitchen zone check — NPCs must not enter kitchen interior or door
function _isKitchenZone(px, py) {
  const tx = Math.floor(px / TILE);
  const ty = Math.floor(py / TILE);
  if (tx <= 23 && ty <= 20) return true;
  if (tx === 24 && ty >= 18 && ty <= 21) return true;  // kitchen door + counter wall
  if (tx === 25 && ty === 21) return true;               // corner under kitchen door
  return false;
}

// Pick a free shelf spot — returns { name, price, tx, ty } or null
// Tracks NPCs already browsing OR walking toward a shelf spot
function _pickFreeShelfSpot(excludeSpot) {
  const occupied = new Set();
  for (const n of deliNPCs) {
    if (n._browseSpot && (n.state === 'browsing_shelf' ||
        (n.state === 'walking' && n._nextState === 'browsing_shelf'))) {
      occupied.add(n._browseSpot.tx + ',' + n._browseSpot.ty);
    }
  }
  if (excludeSpot) occupied.add(excludeSpot.tx + ',' + excludeSpot.ty);

  const free = [];
  for (const shelf of DELI_SHELVES) {
    for (const spot of shelf.spots) {
      if (!occupied.has(spot.tx + ',' + spot.ty)) {
        free.push({ name: shelf.name, price: shelf.price, tx: spot.tx, ty: spot.ty });
      }
    }
  }
  if (free.length === 0) return null;
  return free[Math.floor(Math.random() * free.length)];
}

// Claim a free chair
function _claimChair(npc) {
  const claimed = new Set();
  for (const n of deliNPCs) if (n.claimedChair !== null) claimed.add(n.claimedChair);
  const avail = [];
  for (let i = 0; i < DELI_CHAIRS.length; i++) if (!claimed.has(i)) avail.push(i);
  return avail.length > 0 ? _cRandFromArray(avail) : -1;
}

// Check if there are unclaimed orders on the counter
function _hasUnclaimedCounterOrders() {
  if (typeof cookingState === 'undefined' || !cookingState.counterOrders) return false;
  return cookingState.counterOrders.some(o => !o._claimedByNpc);
}

// ===================== ROUTE BUILDERS =====================
// TRAFFIC LANES:
//   tx:13  — ENTRY lane (NPCs entering deli, left side of door)
//   tx:14  — EXIT lane (NPCs leaving deli, right side of door)
//   tx:26  — MAIN N/S corridor (east of kitchen wall)
//   ty:22  — E/W corridor south of counter wall
//   ty:20  — E/W corridor for dining area access
// LOBBY AREA (ty:22-34): Open space — NPCs can route freely, multiple paths

function _nearestAisleGap(tx) {
  const gaps = [26, 32];
  let best = gaps[0];
  let bestDist = Math.abs(tx - gaps[0]);
  for (let i = 1; i < gaps.length; i++) {
    const d = Math.abs(tx - gaps[i]);
    if (d < bestDist) { bestDist = d; best = gaps[i]; }
  }
  return best;
}

// Route from enter door to pickup counter (Order NPCs)
function _routeEnterToPickup(pickupSpotIdx) {
  const spot = DELI_PICKUP_SPOTS[pickupSpotIdx];
  return [
    { tx: 13, ty: 22 },             // north along entry lane to counter row
    { tx: spot.tx, ty: spot.ty },    // east to pickup spot
  ];
}

// Route from pickup spot to a chair (Order NPCs carry food to seat)
function _routePickupToChair(chairIdx) {
  const ch = DELI_CHAIRS[chairIdx];
  return [
    { tx: 26, ty: 22 },             // east along corridor
    { tx: 26, ty: 20 },             // north to safe horizontal corridor
    { tx: ch.tx, ty: 20 },          // east/west to chair's column
    { tx: ch.tx, ty: ch.ty },       // north/south to chair
  ];
}

// Route from chair to exit door (right side of door)
function _routeChairToExit(chairIdx) {
  const ch = DELI_CHAIRS[chairIdx];
  return [
    { tx: ch.tx, ty: 20 },          // to safe corridor
    { tx: 26, ty: 20 },             // west to main corridor
    { tx: 26, ty: 22 },             // south past counter wall
    { tx: 14, ty: 22 },             // west to exit lane
    { tx: 14, ty: 34 },             // south to exit door
  ];
}

// Route from enter door to shelf spot (Aisle NPCs — uses ty:23 to avoid counter pickup area at ty:22)
function _routeEnterToShelf(spot) {
  const gap = _nearestAisleGap(spot.tx);
  if (gap <= 26) {
    return [
      { tx: 13, ty: 23 },
      { tx: 26, ty: 23 },
      { tx: 26, ty: spot.ty },
      { tx: spot.tx, ty: spot.ty },
    ];
  }
  return [
    { tx: 13, ty: 23 },
    { tx: 26, ty: 23 },
    { tx: 26, ty: 28 },
    { tx: gap, ty: 28 },
    { tx: gap, ty: spot.ty },
    { tx: spot.tx, ty: spot.ty },
  ];
}

// Route between shelf spots
function _routeShelfToShelf(fromTX, fromTY, toSpot) {
  const gap = _nearestAisleGap(fromTX);
  const toGap = _nearestAisleGap(toSpot.tx);
  const route = [];
  if (fromTY === toSpot.ty) {
    route.push({ tx: gap, ty: fromTY });
    if (gap !== toGap) route.push({ tx: toGap, ty: fromTY });
    route.push({ tx: toSpot.tx, ty: toSpot.ty });
  } else {
    route.push({ tx: gap, ty: fromTY });
    route.push({ tx: gap, ty: toSpot.ty });
    route.push({ tx: toSpot.tx, ty: toSpot.ty });
  }
  return route;
}

// Route to exit door for order NPCs (uses ty:22 corridor)
function _routeToExitDoor(fromTX, fromTY) {
  const route = [];
  if (fromTX >= 25) {
    if (fromTY < 22) {
      route.push({ tx: 26, ty: 22 });
    } else if (fromTY >= 24) {
      const gap = _nearestAisleGap(fromTX);
      route.push({ tx: gap, ty: fromTY });
      route.push({ tx: gap, ty: 22 });
    }
    route.push({ tx: 14, ty: 22 });
  }
  route.push({ tx: 14, ty: 34 });
  return route;
}

// Route to exit door for aisle NPCs (uses ty:23 to avoid counter pickup area)
function _routeAisleToExit(fromTX, fromTY) {
  const route = [];
  if (fromTX >= 25) {
    const gap = _nearestAisleGap(fromTX);
    if (fromTY >= 24) {
      route.push({ tx: gap, ty: fromTY });
    }
    route.push({ tx: gap, ty: 23 });
    route.push({ tx: 14, ty: 23 });
  }
  route.push({ tx: 14, ty: 34 });
  return route;
}

// ===================== MOVEMENT =====================
// Browsing NPCs are locked in place — skip them for avoidance
const _deliMoveSkipStates = new Set(['eating', 'spawn_wait', '_despawn', 'browsing_shelf']);
const _deliMoveLaneDisable = new Set(['picking_up', 'browsing_shelf']);

function moveDeliNPC(npc) {
  // 1-tile ahead radar — if another walking NPC is within 1 tile ahead, pause to avoid collision
  if (npc.route && npc.route.length > 0) {
    const wp = npc.route[0];
    const tgtX = wp.tx * TILE + TILE / 2;
    const tgtY = wp.ty * TILE + TILE / 2;
    const mdx = tgtX - npc.x;
    const mdy = tgtY - npc.y;
    const mdist = Math.sqrt(mdx * mdx + mdy * mdy);
    if (mdist > 1) {
      const mnx = mdx / mdist, mny = mdy / mdist;
      for (const other of deliNPCs) {
        if (other === npc) continue;
        if (_deliMoveSkipStates.has(other.state)) continue;
        const ox = other.x - npc.x;
        const oy = other.y - npc.y;
        const od = Math.sqrt(ox * ox + oy * oy);
        if (od > 0 && od < TILE && npc.id > other.id) {
          // Check if other NPC is ahead of us (dot product with movement direction)
          // Only higher-ID NPC yields — lower ID has priority and keeps moving
          const dot = (ox * mnx + oy * mny) / od;
          if (dot > 0.3) {
            // NPC ahead within 1 tile — pause this frame, don't push through
            npc.moving = true;
            return;
          }
        }
      }
    }
  }
  _cMoveNPC(npc, {
    npcList: deliNPCs,
    skipStates: _deliMoveSkipStates,
    kitchenCheck: _isKitchenZone,
    kitchenSafe: { tx: 26, ty: 22 },
    kitchenFallback: [{ tx: 14, ty: 23 }, { tx: 14, ty: 34 }],
    laneMode: 'checked',
    laneDisableStates: _deliMoveLaneDisable,
    pairBehavior: () => 'yield',
  });
}

// ===================== SPAWN =====================

// Spawn an Order NPC (only when food is on counter)
function _spawnOrderNPC() {
  // Claim the first unclaimed order BEFORE spawning
  const order = cookingState.counterOrders.find(o => !o._claimedByNpc);
  if (!order) return null;

  const npc = _cCreateNPC(_deliIdCounter, DELI_SPOTS.enterDoor, DELI_NPC_APPEARANCES,
    DELI_NPC_NAMES, DELI_NPC_CONFIG, {
    purchasedExtras: [],
    claimedChair: null,
    _claimedOrder: null,
    _recipeIngredients: null,
    _laneOffX: 0,
    _laneOffY: 0,
    _role: 'order',
    _pickupSpotIdx: -1,
    hasBag: false,
    _bagItems: [],
    _browseSpot: null,
    _tableFood: false,
    isDeliNPC: true,
  });

  // Claim the order
  order._claimedByNpc = npc.id;
  npc._claimedOrder = order;

  deliNPCs.push(npc);
  return npc;
}

// Spawn an Aisle NPC (enters anytime — but only if free shelf spots exist so they always purchase)
function _spawnAisleNPC() {
  // Don't spawn if no free shelf spots — NPC must always buy something
  if (!_pickFreeShelfSpot(null)) return null;

  const npc = _cCreateNPC(_deliIdCounter, DELI_SPOTS.enterDoor, DELI_NPC_APPEARANCES,
    DELI_NPC_NAMES, DELI_NPC_CONFIG, {
    purchasedExtras: [],
    claimedChair: null,
    _claimedOrder: null,
    _recipeIngredients: null,
    _laneOffX: 0,
    _laneOffY: 0,
    _role: 'aisle',
    _pickupSpotIdx: -1,
    _aisleVisits: 0,
    _pendingPurchase: null,
    _browseSpot: null,
    hasBag: true,     // Aisle NPCs carry a shopping bag
    _bagItems: [],    // Items in the bag (for visual fill)
    _tableFood: false,
    isDeliNPC: true,
  });
  deliNPCs.push(npc);
  return npc;
}

function initDeliNPCs() {
  deliNPCs.length = 0;
  _deliIdCounter.value = 0;
  _deliSpawnState.timer = 0;
  _deliSpawnState.nextInterval = _cRandRange(60, 180);
  _deliAisleSpawnTimer = 0;
  if (typeof cookingState !== 'undefined') {
    cookingState.counterOrders = [];
  }
}

// ===================== AI STATE HANDLERS =====================

const DELI_NPC_AI = {

  // ─── SPAWN_WAIT: Staggered delay before entering ───────
  spawn_wait: (npc) => {
    npc.moving = false;
    if (npc.stateTimer > 0) { npc.stateTimer--; return; }
    npc.state = 'entering';
  },

  // ─── ENTERING: Route depends on NPC role ──────────────
  entering: (npc) => {
    if (npc._role === 'order') {
      // Order NPC — walk to the pickup spot directly in front of their claimed plate
      let spotIdx = 0;
      if (npc._claimedOrder && typeof cookingState !== 'undefined' && cookingState.counterOrders) {
        const orderPos = cookingState.counterOrders.indexOf(npc._claimedOrder);
        if (orderPos >= 0) spotIdx = Math.min(orderPos, DELI_PICKUP_SPOTS.length - 1);
      }
      npc._pickupSpotIdx = spotIdx;
      _cStartRoute(npc, _routeEnterToPickup(spotIdx), 'picking_up', 30);
      return;
    }

    // Aisle NPC — walk to first shelf spot
    const spot = _pickFreeShelfSpot(null);
    if (!spot) {
      // All spots full — leave immediately
      _cStartRoute(npc, [{ tx: 14, ty: 34 }], '_despawn', 0);
      return;
    }
    npc._pendingPurchase = spot;
    npc._browseSpot = { tx: spot.tx, ty: spot.ty };
    _cStartRoute(npc, _routeEnterToShelf(spot),
      'browsing_shelf', _cRandRange(DELI_NPC_CONFIG.browseDuration[0], DELI_NPC_CONFIG.browseDuration[1]));
  },

  // ─── WALKING: Follow route, then transition ────────────
  walking: (npc) => {
    if (npc.route && npc.route.length > 0) return;
    npc.state = npc._nextState || '_despawn';
    npc.stateTimer = npc._nextTimer || 0;
  },

  // ─── PICKING UP: At counter, face plate, grab food ────
  picking_up: (npc) => {
    npc.moving = false;
    npc.dir = 1; // face north toward counter — MUST face plate to pick it up

    // Snap to pickup spot on south side of counter
    if (npc._pickupSpotIdx >= 0 && npc._pickupSpotIdx < DELI_PICKUP_SPOTS.length) {
      const spot = DELI_PICKUP_SPOTS[npc._pickupSpotIdx];
      npc.x = spot.tx * TILE + TILE / 2;
      npc.y = spot.ty * TILE + TILE / 2;
    }

    // Verify NPC is on south side of counter (ty >= 22) — cannot grab from other side
    const npcTY = Math.floor(npc.y / TILE);
    if (npcTY < 22) {
      _cStartRoute(npc, [{ tx: Math.floor(npc.x / TILE), ty: 22 }], 'picking_up', 30);
      return;
    }

    if (npc.stateTimer > 0) { npc.stateTimer--; return; }

    // Pick up food from counter (only once)
    if (!npc.hasFood && npc._claimedOrder) {
      npc.hasFood = true;
      if (npc._claimedOrder.recipeIngredients) {
        npc._recipeIngredients = npc._claimedOrder.recipeIngredients;
      }
      // Remove from counterOrders
      if (typeof cookingState !== 'undefined' && cookingState.counterOrders) {
        const idx = cookingState.counterOrders.indexOf(npc._claimedOrder);
        if (idx >= 0) cookingState.counterOrders.splice(idx, 1);
      }
      npc._claimedOrder = null;
    }

    // Now find a RED SEAT to eat at — must always go to a table
    const chairIdx = _claimChair(npc);
    if (chairIdx < 0) {
      // No seats right now — wait and retry (NPC holds food at counter)
      npc.stateTimer = 60; // retry in 1 second
      return;
    }
    npc.claimedChair = chairIdx;
    npc._pickupSpotIdx = -1;
    _cStartRoute(npc, _routePickupToChair(chairIdx), 'eating', DELI_NPC_CONFIG.eatDuration[0]);
  },

  // ─── EATING: Sitting at red seat with food, plate on table ───
  eating: (npc) => {
    npc.moving = false;
    npc._tableFood = true; // flag for draw.js to render plate on table
    if (npc.claimedChair !== null && npc.claimedChair >= 0) {
      const ch = DELI_CHAIRS[npc.claimedChair];
      npc.x = ch.tx * TILE + TILE / 2;
      npc.y = ch.ty * TILE + TILE / 2;
      npc.dir = ch.sitDir;
    }
    if (npc.stateTimer > 0) { npc.stateTimer--; return; }

    // Done eating — leave
    npc.hasFood = false;
    npc._tableFood = false;
    npc._recipeIngredients = null;
    const chairIdx = npc.claimedChair;
    npc.claimedChair = null;
    if (chairIdx !== null && chairIdx >= 0) {
      _cStartRoute(npc, _routeChairToExit(chairIdx), '_despawn', 0);
    } else {
      _cStartRoute(npc, _routeToExitDoor(Math.floor(npc.x / TILE), Math.floor(npc.y / TILE)), '_despawn', 0);
    }
  },

  // ─── BROWSING SHELF: Aisle NPC locked at spot facing north ──
  browsing_shelf: (npc) => {
    npc.moving = false;
    npc.dir = 1; // face north toward shelf — must face shelf to buy

    // Lock NPC to browse spot (no drifting or corner-sitting)
    if (npc._browseSpot) {
      npc.x = npc._browseSpot.tx * TILE + TILE / 2;
      npc.y = npc._browseSpot.ty * TILE + TILE / 2;
    }

    if (npc.stateTimer > 0) { npc.stateTimer--; return; }

    // Purchase item and add to bag
    if (npc._pendingPurchase) {
      const item = npc._pendingPurchase;
      if (typeof gold !== 'undefined') gold += item.price;
      if (typeof cookingState !== 'undefined' && cookingState.active) {
        cookingState.stats.totalEarned += item.price;
      }
      npc.purchasedExtras.push(item.name);
      npc._bagItems.push({ name: item.name, color: _getAisleColor(item.name) });
      if (typeof hitEffects !== 'undefined') {
        hitEffects.push({ x: npc.x, y: npc.y - 40, life: 30, maxLife: 30, type: 'heal', dmg: '+$' + item.price + ' (' + item.name + ')' });
      }
      npc._pendingPurchase = null;
    }

    // Visit more shelves (up to 3 total)
    if (npc._aisleVisits === undefined) npc._aisleVisits = 0;
    npc._aisleVisits++;
    if (npc._aisleVisits < 3 && Math.random() < 0.6) {
      const spot = _pickFreeShelfSpot(npc._browseSpot);
      if (spot) {
        npc._pendingPurchase = spot;
        const oldSpot = npc._browseSpot;
        npc._browseSpot = { tx: spot.tx, ty: spot.ty };
        _cStartRoute(npc, _routeShelfToShelf(oldSpot.tx, oldSpot.ty, spot),
          'browsing_shelf', _cRandRange(DELI_NPC_CONFIG.browseDuration[0], DELI_NPC_CONFIG.browseDuration[1]));
        return;
      }
    }

    // Done shopping — exit via aisle route (avoids counter area)
    npc._browseSpot = null;
    const aTX = Math.floor(npc.x / TILE);
    const aTY = Math.floor(npc.y / TILE);
    _cStartRoute(npc, _routeAisleToExit(aTX, aTY), '_despawn', 0);
  },

  // ─── DESPAWN WALK: Walking to exit then despawn ────────
  _despawn_walk: (npc) => {
    if (npc.route && npc.route.length > 0) {
      moveDeliNPC(npc);
      return;
    }
    npc.state = '_despawn';
  },
};

// Helper: get a color for bag item visualization
function _getAisleColor(name) {
  switch (name) {
    case 'Frozen':    return '#a0d0f0';
    case 'Snacks':    return '#e0c060';
    case 'Candy':     return '#ff80a0';
    case 'Beverages': return '#60c0a0';
    default:          return '#c0a080';
  }
}

// ===================== MAIN UPDATE =====================
function updateDeliNPCs() {
  if (typeof Scene === 'undefined' || !Scene.inCooking) return;
  if (typeof cookingState === 'undefined' || cookingState.activeRestaurantId !== 'street_deli') return;

  if (!cookingState.counterOrders) cookingState.counterOrders = [];

  // Spawn Order NPCs when food is on counter (check every frame)
  if (_hasUnclaimedCounterOrders() && deliNPCs.length < DELI_NPC_CONFIG.maxNPCs) {
    // Small delay so orders don't get picked up instantly
    _deliSpawnState.timer++;
    if (_deliSpawnState.timer >= 90) { // 1.5 sec delay after food appears
      _spawnOrderNPC();
      _deliSpawnState.timer = 0;
    }
  } else {
    _deliSpawnState.timer = 0;
  }

  // Spawn Aisle NPCs on a separate timer
  _deliAisleSpawnTimer++;
  const aisleNPCCount = deliNPCs.filter(n => n._role === 'aisle').length;
  if (_deliAisleSpawnTimer >= _cRandRange(DELI_NPC_CONFIG.aisleSpawnInterval[0], DELI_NPC_CONFIG.aisleSpawnInterval[1])) {
    if (aisleNPCCount < 4 && deliNPCs.length < DELI_NPC_CONFIG.maxNPCs) {
      _spawnAisleNPC();
    }
    _deliAisleSpawnTimer = 0;
  }

  // Update all NPCs
  for (let i = deliNPCs.length - 1; i >= 0; i--) {
    const npc = deliNPCs[i];

    // Despawn check
    if (npc.state === '_despawn') {
      if (npc.claimedChair !== null) npc.claimedChair = null;
      if (npc._claimedOrder) {
        npc._claimedOrder._claimedByNpc = null;
        npc._claimedOrder = null;
      }
      if (typeof cookingState !== 'undefined' && cookingState.counterOrders) {
        for (let j = cookingState.counterOrders.length - 1; j >= 0; j--) {
          if (cookingState.counterOrders[j]._claimedByNpc === npc.id) {
            cookingState.counterOrders[j]._claimedByNpc = null;
          }
        }
      }
      npc.hasFood = false;
      npc._tableFood = false;
      npc._recipeIngredients = null;
      npc._browseSpot = null;
      deliNPCs.splice(i, 1);
      continue;
    }

    // Movement
    moveDeliNPC(npc);

    // State handler
    const handler = DELI_NPC_AI[npc.state];
    if (handler) handler(npc);

    // Stuck detection — 3 sec stuck → reroute or force exit
    if (npc.moving && npc.route && npc.route.length > 0) {
      npc._stuckFrames = (npc._stuckFrames || 0) + 1;
      if (npc._stuckFrames > 180) {
        npc._stuckFrames = 0;
        if (_isKitchenZone(npc.x, npc.y)) {
          npc.x = 26 * TILE + TILE / 2;
          npc.y = 22 * TILE + TILE / 2;
        }
        // Order NPCs with food: NEVER drop food — reroute to a table instead
        if (npc._role === 'order' && npc.hasFood) {
          const chairIdx = _claimChair(npc);
          if (chairIdx >= 0) {
            if (npc.claimedChair !== null) npc.claimedChair = null;
            npc.claimedChair = chairIdx;
            const curTX = Math.floor(npc.x / TILE);
            const curTY = Math.floor(npc.y / TILE);
            _cStartRoute(npc, _routePickupToChair(chairIdx), 'eating', DELI_NPC_CONFIG.eatDuration[0]);
          } else {
            // No chair available — wait at counter area, retry soon
            npc.state = 'picking_up';
            npc.stateTimer = 60;
            npc.route = null;
          }
        } else {
          // Aisle NPCs or order NPCs without food — clean up and exit
          npc.hasFood = false;
          npc._tableFood = false;
          npc._recipeIngredients = null;
          npc._browseSpot = null;
          if (npc.claimedChair !== null) npc.claimedChair = null;
          if (npc._claimedOrder) {
            npc._claimedOrder._claimedByNpc = null;
            npc._claimedOrder = null;
          }
          const curTX = Math.floor(npc.x / TILE);
          const curTY = Math.floor(npc.y / TILE);
          // Aisle NPCs use ty:23 route to avoid counter, order NPCs use ty:22
          const exitRoute = npc._role === 'aisle'
            ? _routeAisleToExit(curTX, curTY)
            : _routeToExitDoor(curTX, curTY);
          _cStartRoute(npc, exitRoute, '_despawn', 0);
        }
      }
    } else {
      npc._stuckFrames = 0;
    }

    // Idle timeout (not eating/browsing)
    if (!npc.moving && npc.state !== 'eating' && npc.state !== 'browsing_shelf' && npc.state !== 'picking_up') {
      npc._idleTime = (npc._idleTime || 0) + 1;
      if (npc._idleTime > 3600) { // 60 sec idle
        npc._idleTime = 0;
        npc.hasFood = false;
        npc._tableFood = false;
        npc._recipeIngredients = null;
        npc._browseSpot = null;
        if (npc.claimedChair !== null) npc.claimedChair = null;
        if (npc._claimedOrder) {
          npc._claimedOrder._claimedByNpc = null;
          npc._claimedOrder = null;
        }
        const curTX = Math.floor(npc.x / TILE);
        const curTY = Math.floor(npc.y / TILE);
        const idleExitRoute = npc._role === 'aisle'
          ? _routeAisleToExit(curTX, curTY)
          : _routeToExitDoor(curTX, curTY);
        _cStartRoute(npc, idleExitRoute, '_despawn', 0);
      }
    } else {
      npc._idleTime = 0;
    }
  }
}
