// ===================== DELI NPC SYSTEM =====================
// Two NPC types:
//   Order NPC  — ONLY enters when food is on counter. Pick up → sit → eat 15s → leave.
//   Aisle NPC  — Enters anytime. Browses shelves with a bag that fills up. Player gets paid.
//
// Orders are auto-generated by cookingSystem. Player preps food and serves at
// the green SERVE counter. Completed orders appear as plates on the brown counter.
// NO pathfinding — straight-line movement between defined waypoints.

// ===================== APPEARANCE POOL =====================
const DELI_NPC_APPEARANCES = [
  { skin: '#d4a574', hair: '#3a2a1a', shirt: '#4060a0', pants: '#3a3a50' },
  { skin: '#8d5524', hair: '#1a1a1a', shirt: '#a04040', pants: '#2a3a4a' },
  { skin: '#f0c8a0', hair: '#c08040', shirt: '#40a060', pants: '#4a4a5a' },
  { skin: '#c68642', hair: '#4a3020', shirt: '#d0a040', pants: '#3a4a3a' },
  { skin: '#e0b890', hair: '#8a6a40', shirt: '#6040a0', pants: '#3a3a4a' },
  { skin: '#a0764a', hair: '#2a1a0a', shirt: '#a06030', pants: '#4a3a30' },
  { skin: '#f5d0a0', hair: '#d0a060', shirt: '#306060', pants: '#504040' },
  { skin: '#b5835a', hair: '#1a1010', shirt: '#808080', pants: '#2a2a3a' },
];

// Real human names for NPCs
const DELI_NPC_NAMES = [
  'Tyler', 'Hailey', 'Johnny', 'Marcus', 'Sophia', 'Derek', 'Lily', 'Brandon',
  'Emma', 'Chris', 'Maya', 'Jake', 'Olivia', 'Andre', 'Chloe', 'Ethan',
  'Zoe', 'Kevin', 'Rachel', 'Dylan', 'Mia', 'Jordan', 'Sarah', 'Liam',
  'Ava', 'Noah', 'Grace', 'Alex', 'Hannah', 'Ryan', 'Kayla', 'Mason',
];

// ===================== DEFINED SPOTS =====================
const DELI_SPOTS = {
  exit:        { tx: 13, ty: 34 },   // entrance/exit door
  counterArea: { tx: 13, ty: 22 },   // corridor in front of counter
  corridorE:   { tx: 25, ty: 22 },   // east end — past the counter wall
  diningEntry: { tx: 26, ty: 20 },   // gap into dining area
};

// Pickup spots along the brown service counter (ty:22, south of counter wall)
const DELI_PICKUP_SPOTS = [
  { tx: 15, ty: 22 }, { tx: 16, ty: 22 }, { tx: 17, ty: 22 }, { tx: 18, ty: 22 },
];

// Chairs (NPCs sit here) — 2 per side × 4 sides × 2 tables = 16 seats
const DELI_CHAIRS = [
  // Table 1 (28,4)
  { tx: 27, ty: 4,  sitDir: 3 },  { tx: 27, ty: 5,  sitDir: 3 },   // left ×2
  { tx: 31, ty: 4,  sitDir: 2 },  { tx: 31, ty: 5,  sitDir: 2 },   // right ×2
  { tx: 28, ty: 3,  sitDir: 0 },  { tx: 30, ty: 3,  sitDir: 0 },   // top ×2
  { tx: 28, ty: 6,  sitDir: 1 },  { tx: 30, ty: 6,  sitDir: 1 },   // bottom ×2
  // Table 2 (28,17)
  { tx: 27, ty: 17, sitDir: 3 },  { tx: 27, ty: 18, sitDir: 3 },
  { tx: 31, ty: 17, sitDir: 2 },  { tx: 31, ty: 18, sitDir: 2 },
  { tx: 28, ty: 16, sitDir: 0 },  { tx: 30, ty: 16, sitDir: 0 },
  { tx: 28, ty: 19, sitDir: 1 },  { tx: 30, ty: 19, sitDir: 1 },
];

// Aisle browse spots — 4 shelves in 2 rows, NPCs stand below each shelf
const DELI_AISLES = [
  { name: 'Frozen',    price: 4, tx: 29, ty: 26 },   // shelf ty:24-25, browse ty:26
  { name: 'Snacks',    price: 3, tx: 36, ty: 26 },
  { name: 'Candy',     price: 2, tx: 29, ty: 32 },   // shelf ty:30-31, browse ty:32
  { name: 'Beverages', price: 3, tx: 36, ty: 32 },
];

// Cashier spot for retail shoppers (tx:37 keeps NPC body off right wall)
const DELI_CASHIER = { tx: 37, ty: 24 };

// ===================== CONFIG =====================
const DELI_NPC_CONFIG = {
  minNPCs: 0,
  maxNPCs: 6,
  spawnInterval: [180, 420],   // 3-7 sec randomized range (frames at 60fps)
  baseSpeed: 0.77,             // slow relaxed stroll
  speedVariance: 0.14,
  eatDuration:    [900, 900],  // 15 sec at 60fps
  browseDuration: [480, 900],  // 8-15 sec browsing at an aisle
  aisleSpawnInterval: [300, 600], // 5-10 sec between aisle NPC spawns
};

// ===================== STATE =====================
const deliNPCs = [];
const _deliIdCounter = { value: 0 };
const _deliSpawnState = { timer: 0, nextInterval: 600 };
let _deliAisleSpawnTimer = 0;

// ===================== HELPERS =====================

// Kitchen zone check — NPCs must not enter kitchen interior or door
function _isKitchenZone(px, py) {
  const tx = Math.floor(px / TILE);
  const ty = Math.floor(py / TILE);
  if (tx <= 23 && ty <= 20) return true;
  if (tx === 24 && ty >= 19 && ty <= 20) return true;
  return false;
}

// Pick an aisle spot that no other NPC is currently browsing at
function _pickFreeAisle() {
  const occupied = new Set();
  for (const n of deliNPCs) {
    if (n.state === 'browsing_shelf') {
      const ntx = Math.floor(n.x / TILE);
      const nty = Math.floor(n.y / TILE);
      for (let i = 0; i < DELI_AISLES.length; i++) {
        if (DELI_AISLES[i].tx === ntx && DELI_AISLES[i].ty === nty) {
          occupied.add(i);
          break;
        }
      }
    }
  }
  const free = [];
  for (let i = 0; i < DELI_AISLES.length; i++) {
    if (!occupied.has(i)) free.push(i);
  }
  if (free.length === 0) return _cRandFromArray(DELI_AISLES);
  return DELI_AISLES[free[Math.floor(Math.random() * free.length)]];
}

// Claim a free chair
function _claimChair(npc) {
  const claimed = new Set();
  for (const n of deliNPCs) if (n.claimedChair !== null) claimed.add(n.claimedChair);
  const avail = [];
  for (let i = 0; i < DELI_CHAIRS.length; i++) if (!claimed.has(i)) avail.push(i);
  return avail.length > 0 ? _cRandFromArray(avail) : -1;
}

// Check if there are unclaimed orders on the counter
function _hasUnclaimedCounterOrders() {
  if (typeof cookingState === 'undefined' || !cookingState.counterOrders) return false;
  return cookingState.counterOrders.some(o => !o._claimedByNpc);
}

// ===================== ROUTE BUILDERS =====================
// TRAFFIC LANES:
//   tx:13  — ENTRY lane (NPCs walking north)
//   tx:16  — EXIT lane (NPCs leaving)
//   tx:18  — AISLE ENTRY lane
//   tx:26  — MAIN N/S corridor (east of kitchen wall)
//   ty:22  — E/W corridor south of counter wall
//   ty:20  — E/W corridor below dining tables
// AISLE AREA (tx:27+):
//   Shelf row 1: ty:24-25, Browse row 1: ty:26
//   Walkway: ty:27-29
//   Shelf row 2: ty:30-31, Browse row 2: ty:32
//   Gaps: tx:26 (west), tx:32 (between shelf columns)

function _nearestAisleGap(tx) {
  const gaps = [26, 32];
  let best = gaps[0];
  let bestDist = Math.abs(tx - gaps[0]);
  for (let i = 1; i < gaps.length; i++) {
    const d = Math.abs(tx - gaps[i]);
    if (d < bestDist) { bestDist = d; best = gaps[i]; }
  }
  return best;
}

// Route from exit to pickup counter (Order NPCs go straight to counter)
function _routeExitToPickup(pickupSpotIdx) {
  const spot = DELI_PICKUP_SPOTS[pickupSpotIdx];
  return [
    { tx: 13, ty: 22 },             // north along entry lane to counter row
    { tx: spot.tx, ty: spot.ty },    // east to pickup spot
  ];
}

// Route from pickup spot to a chair (Order NPCs carry food to seat)
function _routePickupToChair(pickupSpotIdx, chairIdx) {
  const ch = DELI_CHAIRS[chairIdx];
  return [
    { tx: 26, ty: 22 },             // east along corridor
    { tx: 26, ty: 20 },             // north to safe horizontal corridor
    { tx: ch.tx, ty: 20 },          // east to chair's column
    { tx: ch.tx, ty: ch.ty },       // to chair
  ];
}

// Route from chair to exit (Order NPCs leave after eating)
function _routeChairToExit(chairIdx) {
  const ch = DELI_CHAIRS[chairIdx];
  return [
    { tx: ch.tx, ty: 20 },          // to safe corridor
    { tx: 26, ty: 20 },             // west to main corridor
    { tx: 26, ty: 22 },             // south past counter wall
    { tx: 13, ty: 22 },             // west to entry lane
    { tx: 13, ty: 34 },             // south to exit
  ];
}

// Route from exit to shelf (Aisle NPCs)
function _routeExitToShelf(shelf) {
  const gap = _nearestAisleGap(shelf.tx);
  if (gap <= 26) {
    return [
      { tx: 18, ty: 22 },
      { tx: 26, ty: 22 },
      { tx: 26, ty: shelf.ty },
      { tx: shelf.tx, ty: shelf.ty },
    ];
  }
  return [
    { tx: 18, ty: 22 },
    { tx: 26, ty: 22 },
    { tx: 26, ty: 28 },
    { tx: gap, ty: 28 },
    { tx: gap, ty: shelf.ty },
    { tx: shelf.tx, ty: shelf.ty },
  ];
}

function _routeAisleToAisle(fromTX, fromTY, toAisle) {
  const gap = _nearestAisleGap(fromTX);
  const toGap = _nearestAisleGap(toAisle.tx);
  const route = [];
  if (fromTY === toAisle.ty) {
    route.push({ tx: gap, ty: fromTY });
    if (gap !== toGap) route.push({ tx: toGap, ty: fromTY });
    route.push({ tx: toAisle.tx, ty: toAisle.ty });
  } else {
    route.push({ tx: gap, ty: fromTY });
    route.push({ tx: gap, ty: toAisle.ty });
    route.push({ tx: toAisle.tx, ty: toAisle.ty });
  }
  return route;
}

function _routeToExit(fromTX, fromTY) {
  const route = [];
  if (fromTX >= 25) {
    if (fromTY < 20) {
      route.push({ tx: fromTX, ty: 20 });
    } else if (fromTY >= 22) {
      const gap = _nearestAisleGap(fromTX);
      route.push({ tx: gap, ty: fromTY });
      if (gap !== 26) {
        route.push({ tx: gap, ty: 20 });
        route.push({ tx: 26, ty: 20 });
      } else {
        route.push({ tx: 26, ty: 20 });
      }
    }
    route.push({ tx: 26, ty: 22 });
    route.push({ tx: 13, ty: 22 });
  }
  route.push({ tx: 13, ty: 34 });
  return route;
}

// ===================== MOVEMENT =====================
const _deliMoveSkipStates = new Set(['eating', 'spawn_wait', '_despawn']);
const _deliMoveLaneDisable = new Set(['picking_up']);

function moveDeliNPC(npc) {
  _cMoveNPC(npc, {
    npcList: deliNPCs,
    skipStates: _deliMoveSkipStates,
    kitchenCheck: _isKitchenZone,
    kitchenSafe: { tx: 26, ty: 22 },
    kitchenFallback: [{ tx: 13, ty: 23 }, { tx: 13, ty: 34 }],
    laneMode: 'checked',
    laneDisableStates: _deliMoveLaneDisable,
    pairBehavior: () => 'yield',
  });
}

// ===================== SPAWN =====================

// Spawn an Order NPC (only when food is on counter)
function _spawnOrderNPC() {
  // Claim the first unclaimed order BEFORE spawning
  const order = cookingState.counterOrders.find(o => !o._claimedByNpc);
  if (!order) return null;

  const npc = _cCreateNPC(_deliIdCounter, DELI_SPOTS.exit, DELI_NPC_APPEARANCES,
    DELI_NPC_NAMES, DELI_NPC_CONFIG, {
    purchasedExtras: [],
    claimedChair: null,
    _claimedOrder: null,
    _recipeIngredients: null,
    _laneOffX: (Math.random() - 0.5) * 32,
    _laneOffY: (Math.random() - 0.5) * 32,
    _role: 'order',
    _pickupSpotIdx: -1,
    hasBag: false,
    _bagItems: [],
    isDeliNPC: true,
  });

  // Claim the order
  order._claimedByNpc = npc.id;
  npc._claimedOrder = order;

  deliNPCs.push(npc);
  return npc;
}

// Spawn an Aisle NPC (enters anytime)
function _spawnAisleNPC() {
  const npc = _cCreateNPC(_deliIdCounter, DELI_SPOTS.exit, DELI_NPC_APPEARANCES,
    DELI_NPC_NAMES, DELI_NPC_CONFIG, {
    purchasedExtras: [],
    claimedChair: null,
    _claimedOrder: null,
    _recipeIngredients: null,
    _laneOffX: (Math.random() - 0.5) * 32,
    _laneOffY: (Math.random() - 0.5) * 32,
    _role: 'aisle',
    _pickupSpotIdx: -1,
    _aisleVisits: 0,
    _pendingPurchase: null,
    hasBag: true,     // Aisle NPCs carry a shopping bag
    _bagItems: [],    // Items in the bag (for visual fill)
    isDeliNPC: true,
  });
  deliNPCs.push(npc);
  return npc;
}

function initDeliNPCs() {
  deliNPCs.length = 0;
  _deliIdCounter.value = 0;
  _deliSpawnState.timer = 0;
  _deliSpawnState.nextInterval = _cRandRange(60, 180);
  _deliAisleSpawnTimer = 0;
  if (typeof cookingState !== 'undefined') {
    cookingState.counterOrders = [];
  }
}

// ===================== AI STATE HANDLERS =====================

const DELI_NPC_AI = {

  // ─── SPAWN_WAIT: Staggered delay before entering ───────
  spawn_wait: (npc) => {
    npc.moving = false;
    if (npc.stateTimer > 0) { npc.stateTimer--; return; }
    npc.state = 'entering';
  },

  // ─── ENTERING: Route depends on NPC role ──────────────
  entering: (npc) => {
    if (npc._role === 'order') {
      // Order NPC — walk straight to pickup counter
      const spotIdx = Math.floor(Math.random() * DELI_PICKUP_SPOTS.length);
      npc._pickupSpotIdx = spotIdx;
      _cStartRoute(npc, _routeExitToPickup(spotIdx), 'picking_up', 30);
      return;
    }

    // Aisle NPC — walk to first shelf
    const shelf = _pickFreeAisle();
    npc._pendingPurchase = shelf;
    _cStartRoute(npc, _routeExitToShelf(shelf),
      'browsing_shelf', _cRandRange(DELI_NPC_CONFIG.browseDuration[0], DELI_NPC_CONFIG.browseDuration[1]));
  },

  // ─── WALKING: Follow route, then transition ────────────
  walking: (npc) => {
    if (npc.route && npc.route.length > 0) return;
    npc.state = npc._nextState || '_despawn';
    npc.stateTimer = npc._nextTimer || 0;
  },

  // ─── PICKING UP: At counter, brief pause, grab food ───
  picking_up: (npc) => {
    npc.moving = false;
    npc.dir = 1; // face north toward counter

    // Snap to pickup spot
    if (npc._pickupSpotIdx >= 0 && npc._pickupSpotIdx < DELI_PICKUP_SPOTS.length) {
      const spot = DELI_PICKUP_SPOTS[npc._pickupSpotIdx];
      npc.x = spot.tx * TILE + TILE / 2;
      npc.y = spot.ty * TILE + TILE / 2;
    }

    if (npc.stateTimer > 0) { npc.stateTimer--; return; }

    // Pick up food from counter
    npc.hasFood = true;
    if (npc._claimedOrder) {
      if (npc._claimedOrder.recipeIngredients) {
        npc._recipeIngredients = npc._claimedOrder.recipeIngredients;
      }
      // Remove from counterOrders
      if (typeof cookingState !== 'undefined' && cookingState.counterOrders) {
        const idx = cookingState.counterOrders.indexOf(npc._claimedOrder);
        if (idx >= 0) cookingState.counterOrders.splice(idx, 1);
      }
      npc._claimedOrder = null;
    }

    // Now find a seat to eat at
    const chairIdx = _claimChair(npc);
    if (chairIdx < 0) {
      // No seats — just exit with food
      npc._pickupSpotIdx = -1;
      _cStartRoute(npc, _routeToExit(Math.floor(npc.x / TILE), Math.floor(npc.y / TILE)), '_despawn', 0);
      return;
    }
    npc.claimedChair = chairIdx;
    npc._pickupSpotIdx = -1;
    _cStartRoute(npc, _routePickupToChair(0, chairIdx), 'eating', DELI_NPC_CONFIG.eatDuration[0]);
  },

  // ─── EATING: Sitting at table with food, 15 sec ───────
  eating: (npc) => {
    npc.moving = false;
    if (npc.claimedChair !== null && npc.claimedChair >= 0) {
      const ch = DELI_CHAIRS[npc.claimedChair];
      npc.x = ch.tx * TILE + TILE / 2;
      npc.y = ch.ty * TILE + TILE / 2;
      npc.dir = ch.sitDir;
    }
    if (npc.stateTimer > 0) { npc.stateTimer--; return; }

    // Done eating — leave
    npc.hasFood = false;
    npc._recipeIngredients = null;
    const chairIdx = npc.claimedChair;
    npc.claimedChair = null;
    if (chairIdx !== null && chairIdx >= 0) {
      _cStartRoute(npc, _routeChairToExit(chairIdx), '_despawn', 0);
    } else {
      _cStartRoute(npc, _routeToExit(Math.floor(npc.x / TILE), Math.floor(npc.y / TILE)), '_despawn', 0);
    }
  },

  // ─── BROWSING SHELF: Aisle NPC standing at shelf ──────
  browsing_shelf: (npc) => {
    npc.moving = false;
    npc.dir = 1; // face shelves (north)
    if (npc.stateTimer > 0) { npc.stateTimer--; return; }

    // Purchase item and add to bag
    if (npc._pendingPurchase) {
      const item = npc._pendingPurchase;
      if (typeof gold !== 'undefined') gold += item.price;
      if (typeof cookingState !== 'undefined' && cookingState.active) {
        cookingState.stats.totalEarned += item.price;
      }
      npc.purchasedExtras.push(item.name);
      npc._bagItems.push({ name: item.name, color: _getAisleColor(item.name) });
      if (typeof hitEffects !== 'undefined') {
        hitEffects.push({ x: npc.x, y: npc.y - 40, life: 30, maxLife: 30, type: 'heal', dmg: '+$' + item.price + ' (' + item.name + ')' });
      }
      npc._pendingPurchase = null;
    }

    // Visit more shelves (up to 3 total)
    if (npc._aisleVisits === undefined) npc._aisleVisits = 0;
    npc._aisleVisits++;
    if (npc._aisleVisits < 3 && Math.random() < 0.6) {
      const aisle = _pickFreeAisle();
      npc._pendingPurchase = aisle;
      const curTX = Math.floor(npc.x / TILE);
      const curTY = Math.floor(npc.y / TILE);
      _cStartRoute(npc, _routeAisleToAisle(curTX, curTY, aisle),
        'browsing_shelf', _cRandRange(DELI_NPC_CONFIG.browseDuration[0], DELI_NPC_CONFIG.browseDuration[1]));
      return;
    }

    // Done shopping — exit
    const aTX = Math.floor(npc.x / TILE);
    const aTY = Math.floor(npc.y / TILE);
    _cStartRoute(npc, _routeToExit(aTX, aTY), '_despawn', 0);
  },

  // ─── DESPAWN WALK: Walking to exit then despawn ────────
  _despawn_walk: (npc) => {
    if (npc.route && npc.route.length > 0) {
      moveDeliNPC(npc);
      return;
    }
    npc.state = '_despawn';
  },
};

// Helper: get a color for bag item visualization
function _getAisleColor(name) {
  switch (name) {
    case 'Frozen':    return '#a0d0f0';
    case 'Snacks':    return '#e0c060';
    case 'Candy':     return '#ff80a0';
    case 'Beverages': return '#60c0a0';
    default:          return '#c0a080';
  }
}

// ===================== MAIN UPDATE =====================
function updateDeliNPCs() {
  if (typeof Scene === 'undefined' || !Scene.inCooking) return;
  if (typeof cookingState === 'undefined' || cookingState.activeRestaurantId !== 'street_deli') return;

  if (!cookingState.counterOrders) cookingState.counterOrders = [];

  // Spawn Order NPCs when food is on counter (check every frame)
  if (_hasUnclaimedCounterOrders() && deliNPCs.length < DELI_NPC_CONFIG.maxNPCs) {
    // Small delay so orders don't get picked up instantly
    _deliSpawnState.timer++;
    if (_deliSpawnState.timer >= 90) { // 1.5 sec delay after food appears
      _spawnOrderNPC();
      _deliSpawnState.timer = 0;
    }
  } else {
    _deliSpawnState.timer = 0;
  }

  // Spawn Aisle NPCs on a separate timer
  _deliAisleSpawnTimer++;
  const aisleNPCCount = deliNPCs.filter(n => n._role === 'aisle').length;
  if (_deliAisleSpawnTimer >= _cRandRange(DELI_NPC_CONFIG.aisleSpawnInterval[0], DELI_NPC_CONFIG.aisleSpawnInterval[1])) {
    if (aisleNPCCount < 3 && deliNPCs.length < DELI_NPC_CONFIG.maxNPCs) {
      _spawnAisleNPC();
    }
    _deliAisleSpawnTimer = 0;
  }

  // Update all NPCs
  for (let i = deliNPCs.length - 1; i >= 0; i--) {
    const npc = deliNPCs[i];

    // Despawn check
    if (npc.state === '_despawn') {
      if (npc.claimedChair !== null) npc.claimedChair = null;
      if (npc._claimedOrder) {
        npc._claimedOrder._claimedByNpc = null;
        npc._claimedOrder = null;
      }
      if (typeof cookingState !== 'undefined' && cookingState.counterOrders) {
        for (let j = cookingState.counterOrders.length - 1; j >= 0; j--) {
          if (cookingState.counterOrders[j]._claimedByNpc === npc.id) {
            cookingState.counterOrders[j]._claimedByNpc = null;
          }
        }
      }
      npc.hasFood = false;
      npc._recipeIngredients = null;
      deliNPCs.splice(i, 1);
      continue;
    }

    // Movement
    moveDeliNPC(npc);

    // State handler
    const handler = DELI_NPC_AI[npc.state];
    if (handler) handler(npc);

    // Stuck detection
    if (npc.moving && npc.route && npc.route.length > 0) {
      npc._stuckFrames = (npc._stuckFrames || 0) + 1;
      if (npc._stuckFrames > 600) { // 10 sec stuck
        npc._stuckFrames = 0;
        npc.hasFood = false;
        npc._recipeIngredients = null;
        if (npc.claimedChair !== null) npc.claimedChair = null;
        if (npc._claimedOrder) {
          npc._claimedOrder._claimedByNpc = null;
          npc._claimedOrder = null;
        }
        if (_isKitchenZone(npc.x, npc.y)) {
          npc.x = 26 * TILE + TILE / 2;
          npc.y = 22 * TILE + TILE / 2;
        }
        const curTX = Math.floor(npc.x / TILE);
        const curTY = Math.floor(npc.y / TILE);
        _cStartRoute(npc, _routeToExit(curTX, curTY), '_despawn', 0);
      }
    } else {
      npc._stuckFrames = 0;
    }

    // Idle timeout (not eating/browsing)
    if (!npc.moving && npc.state !== 'eating' && npc.state !== 'browsing_shelf' && npc.state !== 'picking_up') {
      npc._idleTime = (npc._idleTime || 0) + 1;
      if (npc._idleTime > 3600) { // 60 sec idle
        npc._idleTime = 0;
        npc.hasFood = false;
        npc._recipeIngredients = null;
        if (npc.claimedChair !== null) npc.claimedChair = null;
        if (npc._claimedOrder) {
          npc._claimedOrder._claimedByNpc = null;
          npc._claimedOrder = null;
        }
        const curTX = Math.floor(npc.x / TILE);
        const curTY = Math.floor(npc.y / TILE);
        _cStartRoute(npc, _routeToExit(curTX, curTY), '_despawn', 0);
      }
    } else {
      npc._idleTime = 0;
    }
  }
}
